spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    AccessTokenExpiration: 7200 # 5m
    RefreshTokenExpiration: 604800 # 7d
  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
